# Generated by Django 2.2.3 on 2019-07-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20190730_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created_tweet',
            new_name='created_comment',
        ),
    ]
