# Generated by Django 2.2.3 on 2019-08-12 16:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='image',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='image_from_cl',
            field=cloudinary.models.CloudinaryField(default='image/upload/c_fit,h_150,r_20,w_150/v1565600435/non_existing_id.png', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
